import { Poi } from "@/components/pois-columns"

export const samplePois: Poi[] = [
    {
        id: "1",
        name: "Barikoi Office",
        address: "House 42, Road 5, Block B, Banani, Dhaka",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.9103,
        longitude: 90.4125,
    },
    {
        id: "2",
        name: "Coffee Express",
        address: "Shop 3, Level 2, Jamuna Future Park, Dhaka",
        image: "/placeholder-image.jpg",
        status: "pending",
        latitude: 23.8103,
        longitude: 90.5125,
    },
    {
        id: "3",
        name: "Dhaka University",
        address: "Nilkhet Rd, Dhaka 1000",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.8103,
        longitude: 90.4135,
    },
    {
        id: "4",
        name: "National Museum",
        address: "Shahbag, Dhaka 1000",
        image: "/placeholder-image.jpg",
        status: "invalid",
        latitude: 23.8109,
        longitude: 90.4195,
    },
    {
        id: "5",
        name: "Lakeshore Hotel",
        address: "Road 41, House 11, Gulshan 2, Dhaka",
        image: "/placeholder-image.jpg",
        status: "pending",
        latitude: 23.8903,
        longitude: 90.4925,
    },
    {
        id: "6",
        name: "North End Coffee Roasters",
        address: "House 4, Road 13/C, Block E, Banani, Dhaka",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.8903,
        longitude: 90.4025,
    },
    {
        id: "7",
        name: "Jamuna Future Park",
        address: "Ka-244, Kuril, Progoti Shoroni, Baridhara, Dhaka",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.8993,
        longitude: 90.40259,
    },
    {
        id: "8",
        name: "Bashundhara City Shopping Mall",
        address: "3 No Tejturi Bazar West, Panthapath, Dhaka",
        image: "/placeholder-image.jpg",
        status: "pending",
        latitude: 23.81039,
        longitude: 90.41256,
    },
    {
        id: "9",
        name: "Hatirjheel",
        address: "Hatirjheel, Dhaka",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.81163,
        longitude: 90.40256,
    },
    {
        id: "10",
        name: "Jatiya Sangsad Bhaban",
        address: "Sher-e-Bangla Nagar, Dhaka",
        image: "/placeholder-image.jpg",
        status: "valid",
        latitude: 23.81136,
        longitude: 90.46125,
    },
] 